import '@mantine/core/styles.css';
import { ColorSchemeScript, mantineHtmlProps, MantineProvider } from '@mantine/core';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppShellExample1 from '@/components/ui/appshelltest';




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   /*  <html lang="en"  {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MantineProvider>
        
        <nav>
          
          <Group gap="md" justify="center">
              <Nav/>
              <Button variant="filled" leftSection={<IconHome size="1rem" />}  component={Link} href="/test2">Test2</Button>
              <Button variant="outline" component={Link} href="/test3">Test3</Button>
              <Button variant="outline" component={Link} href="/test4">Test4</Button>
          </Group>
        </nav>
        {children}
        </MantineProvider>
      </body>
    </html> */
<html lang="en"  {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
  <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    <MantineProvider>
    <AppShellExample1>
      {children}
    </AppShellExample1>
    </MantineProvider>
  </body>
</html>
  );
}
